name: beast

channels:
    - astropy

dependencies:
    - python>=2.7
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - pytables
    - pytest-mpl
    - sphinx-astropy
    - dust_extinction
#   - pip:
#       - dependency_from_pip
